# Input data 

## list of bam files for target samples
TARGET_BAM: "test/INPUT/BAM/bamlist" # BAM.BAI IS REQUIRED BY GLIMPSE
## reference genome
REFERENCE_SEQ: "test/INPUT/REF/chr15_ref_modN.fa"
## reference panel in vcf.gz file, index file is required
REFERENCE_VCFGZ: "test/INPUT/REF/ref_test.vcf.gz" 
## ground truth SNP data in vcf.gz file, optional
GROUNDTRUTH: "test/INPUT/REF/test_truth.vcf.gz"


# Software parameters
OUTPUT_DIR: "test/OUTPUT"
PREFIX_NAME: "test_impute"

IMPUTATION: # True/False
    BEAGLE: True
    GLIMPSE: True
    STITCH: True
    GENEIMP: False
    QUILT: True

NGSRELATE:
    MIN_MAF: 0.01
    THREADS: 6

KGD:
    THREADS: 6

BAM2VCF: # BY BCFTOOLS MPILEUP
    THREADS: 6

FILTERVCF_TARGET: # BY BCFTOOLS FILTER
    MIN_QUAL: 30
    THREADS: 6

REF_BEAGLE_PHASING:
    PARAM: "em=true"
    THREADS: 6

BEAGLE:
    PARAM: "em=true"
    THREADS: 6


GLIMPSE:
    GLIMPSE:
    GLIMPSE_CHUNK_PARAM: ""
    GLIMPSE_SPLIT_REFERENCE_PARAM: ""
    GLIMPSE_PHASE_PARAM: ""
    GLIMPSE_LIGATE_PARAM: ""
    THREADS: 6


STITCH:
    NHAP: 5 # REQUIRED
    NGEN: 50 # REQUIRED
    OTHER: "--expRate=1"
    THREADS: 6

GENEIMP:
    HAP: 10
    KL: 50
    FLANKSIZE: 0.5
    FILTER: "pairrand"
    THREADS: 6

QUILT:
    WINDOW_SIZE: 5000000
    BUFFER_SIZE: 100000
    NGEN: 50
    OTHER: "--expRate=1"
    THREADS: 6
    MEM_MB: 8G

STAIRWAY_PLOT:
    POPFILE: "test/INPUT/pops_file.txt"
    SEQUENCE_LENGTH: 10000000
    MUT_RATE: 1e-7
    THREADS: 6
