# Input data 
## list of bam files for target samples
TARGET_BAM: "test/INPUT/BAM/bamlist" # BAM.BAI IS REQUIRED BY GLIMPSE
## reference genome
REFERENCE_SEQ: "test/INPUT/REF/chr15_ref_modN.fa"
## reference panel in vcf.gz file, index file is required
REFERENCE_VCFGZ: "test/INPUT/REF/ref_test.vcf.gz" 
## ground truth SNP data in vcf.gz file, optional
GROUNDTRUTH: "test/INPUT/REF/test_truth.vcf.gz"


# Output directory and prefix for output files
OUTPUT_DIR: "test/OUTPUT"
PREFIX_NAME: "test_impute"

# Choose imputation tools to run
IMPUTATION: # True/False to perform or not
    BEAGLE: True
    GLIMPSE: True
    STITCH: True
    GENEIMP: False
    QUILT: True

# Software parameters
NGSRELATE:
    MIN_MAF: 0.01 # minimum MAF used for NgsRelate relatedness and inbreeding estimation
    THREADS: 6

KGD:
    THREADS: 6

BAM2VCF: # BY BCFTOOLS MPILEUP
    THREADS: 6

FILTERVCF_TARGET: # BY BCFTOOLS FILTER
    MIN_QUAL: 30 # minimum QUAL filter for target VCF
    THREADS: 6

REF_BEAGLE_PHASING:
    PARAM: "em=true" # parameters specified here, or "" for default settings
    THREADS: 6

BEAGLE:
    PARAM: "config/beagle_param.csv" # a csv file containing parameters in columns and values in rows, or "" for default settings
    THREADS: 6


GLIMPSE:
    GLIMPSE_CHUNK_PARAM: "" # parameters specified here, or "" for default settings
    GLIMPSE_SPLIT_REFERENCE_PARAM: "" # parameters specified here, or "" for default settings
    GLIMPSE_PHASE_PARAM: "config/glimpsePHASE_param.csv" # a csv file containing parameters in columns and values in rows, or "" for default settings
    GLIMPSE_LIGATE_PARAM: "" # parameters specified here, or "" for default settings
    THREADS: 6


STITCH:
    PARAM: "config/stitch_param.csv" # a csv file containing parameters in columns and values in rows, or "" for default settings
    THREADS: 6

GENEIMP:
    PARAM: "config/geneimp_param.csv" # a csv file containing parameters in columns and values in rows, or "" for default settings
    THREADS: 6

QUILT:
    WINDOW_SIZE: 1000000 ## options --regionStart/--regionEnd are required by QUILT, but will be automatically decided in the pipeline based on this parameter
    PARAM: "config/quilt_param.csv" # a csv file containing parameters in columns and values in rows, or "" for default settings
    THREADS: 6
    # MEM_MB: 8G

STAIRWAY_PLOT:
    POPFILE: "test/INPUT/pops_file.txt" # a file containing in each row one individual name and its population name (no header/column name)
    SEQUENCE_LENGTH: 10000000 # length of the reference sequence
    MUT_RATE: 1e-7 # mutation rate
    THREADS: 6
